// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Novusnet.Infraestructura.AccesoDatos;

public partial class Cliente
{
    public int pk_cliente { get; set; }

    public string cli_cedula { get; set; }

    public string cli_nombre { get; set; }

    public string cli_apellido { get; set; }

    public string cli_telefono { get; set; }

    public string cli_email { get; set; }

    public string cli_direccion { get; set; }

    public string cli_referencia_ubicacion { get; set; }

    public DateTime? cli_fecha_registro { get; set; }

    public int? cli_activo { get; set; }
    [JsonIgnore]

    public virtual ICollection<SServicio> SServicio { get; set; } = new List<SServicio>();
}