// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novusnet.Infraestructura.AccesoDatos;

public partial class Logging
{
    public int pk_logging { get; set; }

    public string log_user { get; set; }

    public string log_password { get; set; }

    public int fk_Empleado { get; set; }

    public virtual Empleado fk_EmpleadoNavigation { get; set; }
}