// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Novusnet.Infraestructura.AccesoDatos;

public partial class Material
{
    public int pk_material { get; set; }

    public string ma_codigo { get; set; }

    public string ma_nombre { get; set; }

    public string ma_descripcion { get; set; }

    public decimal? ma_precio_unitario { get; set; }

    public int? ma_stock_actual { get; set; }

    public int? ma_stock_minimo { get; set; }

    public string ma_duracion { get; set; }
    [JsonIgnore]

    public virtual ICollection<Orden_Material> Orden_Material { get; set; } = new List<Orden_Material>();
}