// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novusnet.Infraestructura.AccesoDatos;

public partial class Orden_Trabajo
{
    public int pk_orden_trabajo { get; set; }

    public string otra_codigo { get; set; }

    public string otra_descripcion { get; set; }

    public DateOnly? otra_fecha_registro { get; set; }

    public DateOnly? otra_fecha_programada { get; set; }

    public string otra_tiempo_estimado { get; set; }

    public string otra_estado { get; set; }

    public string otra_prioridad { get; set; }

    public int fk_Empleado { get; set; }

    public int fk_servicio { get; set; }

    public virtual ICollection<Orden_Material> Orden_Material { get; set; } = new List<Orden_Material>();

    public virtual Empleado fk_EmpleadoNavigation { get; set; }

    public virtual Servicio fk_servicioNavigation { get; set; }
}