// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novusnet.Infraestructura.AccesoDatos;

public partial class Servicio
{
    public int pk_servicio { get; set; }

    public string ser_nombre { get; set; }

    public decimal? ser_precio { get; set; }

    public string ser_descripcion { get; set; }

    public int? ser_requiere_material { get; set; }

    public string ser_tipo_factura { get; set; }

    public int fk_cliente { get; set; }

    public virtual ICollection<Orden_Trabajo> Orden_Trabajo { get; set; } = new List<Orden_Trabajo>();

    public virtual Cliente fk_clienteNavigation { get; set; }
}